### ISSUE TITLE
FahCore_17 WUs aren't being rendered.

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-client-pub#1112]
Trac | Data
---: | :---
Ticket | 1112
Reported by | @PantherX
Status | reopened
Component | FAHViewer
Priority | 5

Please note that if you are processing FahCore_17 WUs and open the FAHViewer, there isn't any protein being displayed; the demo one or the original one.

Additional Details -> https://foldingforum.org/viewtopic.php?f=94&t=25600

**Comment by jcoffland** [comment]
This is a problem with the core not the client. This core is not used much any more anyway.

**Comment by bb30994** [comment]
The same is true for all GPU cores.
