### ISSUE TITLE
Remember finish state through restart

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-client-pub#1124]
Trac | Data
---: | :---
Ticket | 1124
Reported by | @bb30994
Status | accepted
Component | FAHClient
Priority | 5

I'm opening a new ticket since #1100 somehow included only "pause" whereas we originally proposed doing the same for Finish as you've done for Pause.

As far as I'm concerned, Finish is more important than Pause, although there's no reason to compare them if they both eventually work.

**Comment by jcoffland** [comment]
We will leave this as is.

**Comment by bb30994** [comment]
There's a distinction between a FINISH which, in fact, uploaded a completed WU (and perhaps shut down) and a FINISH which was paused or rebooted without ever finishing the active WU.  The FINISH condition should be cleared whenever the active WU is actually completed and not before.
