### ISSUE TITLE
Display of log fails after finding non-English characters

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-client-pub#1131]
Trac | Data
---: | :---
Ticket | 1131
Reported by | @bb30994
Status | new
Component | FAHClient
Priority | 5

Report of IP address from ISP is given in Chinese characters which causes FAHControl to display blank information.

See https://foldingforum.org/viewtopic.php?f=96&t=26258

**Comment by bb30994** [comment]
The FAHCores issue messages containing the text color attributes.  Do these special characters count as non-English?

**Comment by jcoffland** [comment]
Should be fixed in v7.4.15.
