### ISSUE TITLE
"(not configured)" status only waits one minute

### ISSUE THREAD

**Issue by jcoffland** [FoldingAtHome/fah-client-pub#1136]
Trac | Data
---: | :---
Ticket | 1136
Reported by | @bb30994
Status | new
Component | FAHClient
Priority | 5

On a fresh install, it is impossible to type a passkey twice before the client proceeds to download WUs, thereby guaranteeing that no bonus can be earned on the first WUs.

**Comment by bb30994** [comment]
See alternative: https://github.com/FoldingAtHome/fah-client-pub/issues/928

**Comment by jcoffland** [comment]
As I understand it, the only problem here is that a user might not get a bonus for their first WU.  This mainly annoys testers who regularly reinstall.

Consider the alternative.  What if we waited 5mins?  A new user would probably have moved on to something else by then.  Suddenly F@H starts folding.  They are really going to wonder what the heck is going on and likely get angry.

Currently this is not a high priority item but please feel free to convince me otherwise.

**Comment by jcoffland** [comment]
I don't think we want this.
