### ISSUE TITLE
Core_A4 now retries rather than sending back a partial WU.

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-client-pub#1143]
I'm not sure who does Core_a4, but it looks like a change to the wrapper has created confusing messages.  Gromacs USED TO send back partial WUs.  Now it retries from the last checkpoint, and in this case, it was successful.

The message "Going to send back what have done -- stepsTotalG=500000" is false.  At this point, nothing was sent.

15:46:20:WU01:FS00:0xa4:Completed 165000 out of 500000 steps  (33%)
16:22:51:WU01:FS00:0xa4:Completed 170000 out of 500000 steps  (34%)
16:59:09:WU01:FS00:0xa4:Gromacs cannot continue further.
16:59:09:WU01:FS00:0xa4:Going to send back what have done -- stepsTotalG=500000
16:59:09:WU01:FS00:0xa4:Work fraction=0.3500 steps=500000.
...
16:59:25:WARNING:WU01:FS00:FahCore returned: UNKNOWN_ENUM (-1073741819 = 0xc0000005)
16:59:25:WU01:FS00:Starting
...
16:59:35:WU01:FS00:0xa4:- Previous termination of core was improper.
...
16:59:36:WU01:FS00:0xa4:Entering M.D.
...
16:59:44:WU01:FS00:0xa4:Completed 173840 out of 500000 steps  (34%)
17:07:56:WU01:FS00:0xa4:Completed 175000 out of 500000 steps  (35%)

**Comment by jcoffland** [comment]
I don't understand what the problem is here.  Is this any issue with the new alpha client?  Or is it a problem with the core?

**Comment by bb30994** [comment]
The message "0xa4:Going to send back what have done --..." is now obsolete due to an improvement in the way (presumably) the wrapper handles this situation.  I'm not sure who owns that message.

**Comment by jcoffland** [comment]
This is a Gromacs core issue.
