### ISSUE TITLE
Reformat CUDA Version number.

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-client-pub#1151]
V7.4.4: "CUDA Driver: 7050"
V7.4.9: Is formatted as x.0, not x.050.

**Comment by jcoffland** [comment]
This needs more clarification.  What's the output of v7.4.9 and what is the expected output?

**Comment by jcoffland** [comment]
Also, is this just a cosmetic issue?

**Comment by bb30994** [comment]
It's more than a cosmetic issue because it is missing essential information.  Both 7000 and 7050 are in the field.

{\[I still can't test it on Linux.]
