### ISSUE TITLE
Redefine `normal` WU size to be larger than 10 MiB

### ISSUE THREAD

**Issue by jchodera** [FoldingAtHome/fah-client-pub#1154]
Modern broadband connections mean we should increase the value of `normal` WU sizes to be more than 10 MiB in [this code](https://github.com/FoldingAtHome/fah-client/blob/master/src/fah/client/slot/Slot.cpp#L693-L703).

**Comment by jchodera** [comment]
Maybe 20-25 MiB would be reasonable?

**Comment by jcoffland** [comment]
I've redefined ``normal`` to mean 25MiB.  This will be the case in the v7.4.16 release.

**Comment by jchodera** [comment]
Awesome!
