### ISSUE TITLE
Communications between FAHClient & FAHControl failed

### ISSUE THREAD

**Issue by bollix47** [FoldingAtHome/fah-client-pub#1155]
[Communication_slack_convo.pdf](https://github.com/FoldingAtHome/fah-client-pub/files/52851/Communication_slack_convo.pdf)

Basically the 7.4.4 client stopped communicating with FAHControl & HFM but still had communication with the various cores running until one core was finished then nothing else was logged for that slot.

Please see: https://foldingathome.slack.com/archives/10100/p1449295792000134
and the following posts.

I've attached a PDF of the relevant conversation in case Slack deletes the above link and I have it stored locally should it be needed.

The following is all that John was able to see in the info that the Dumping returned:

2238:08:17:40:I2:Request WORK_DUMPED (575)
2238:08:17:40:I2:Client: 'bollix47=0xf5880b465452f585@99.244.67.141:59391' WORK_DUMPED (575)
2238:08:17:40:I1:Retrying failed job 0x55c68f1cf5f3c61b-76 (0 previous retries)
2238:08:17:40:I3:Response WORK_ACK (400)

**Comment by bb30994** [comment]
Hmmm.

There's a known problem of FAHClient stopping communications with Stanford when an upload or download is rudely interrupted, fixable only by restarting FAHClient after restoring communications.

I've seen communications with the local host (127.0.0 1) permanently interrupted too, (fixable only by restarting FAHClient) but that's extremely rare compared to the first problem.

Do you suppose they're, in fact, the same problem?  We'd have to devise some way of rudely interrupting communications with the local host to test that theory.  I don't know how to do that..


Bruce
-
-
-


---------- Original Message ----------

**Comment by bollix47** [comment]
Although I did not check specifically I wondered it maybe the client just could not shutdown the core for some reason but kept trying ... thus showing higher than usual cpu usage for the client which totow stated he had seen but that is speculation on my part so I`ll leave it to the experts. It does appear to be repeatable as at least three of us all had the same problem under the same circumstances. i.e. 1 or 2 GPUs running core 18 or core 21 and a 10190 running on 6 threads of an 8 thread CPU.

**Comment by ChristianVirtual** [comment]
Just had the same stuck, no remote or local access via telnet anymore, 100% for fahclient on Ubuntu 12.04, client 7.3.6. Restart not helping, stuck again

**Comment by jcoffland** [comment]
This should be fixed in v7.4.15.
