### ISSUE TITLE
Client should ensure that GPUs are actually present before allowing GPU-core projects

### ISSUE THREAD

**Issue by jchodera** [FoldingAtHome/fah-client-pub#1159]
See https://github.com/FoldingAtHome/openmm-core/issues/116

The client should detect that no GPU device is available long before it gets to the point of launching a GPU core expecting to find a device that isn't there.

**Comment by jcoffland** [comment]
The client only reports information to the AS.  The AS is responsible for analyzing this information and deciding if it can run a particular WU.  I believe all the necessary information is already available to make these decisions with out adding complexity to the client code.

Reopen this if you strongly disagree.

**Comment by jchodera** [comment]
Did you look at FoldingAtHome/openmm-core#116 ?
