### ISSUE TITLE
FAHContrrol continually switches between Connecting and Online,

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-client-pub#1163]
The FAHControl program is trying to connect to a remote FAHClient.  The status repeatedly switches switches between Connecting and Online (or Connecting/Updating/Online, depending on which part of the screen you're looking at).  

The status page displays briefly (not long enough to read the information) before refreshing it again.

That copy of FAHControl works fine with other remote FAHClients as well as the local copy.

Telnet to the remote port connects but I don't know what queries to submit.

It's conceivable that the problem is a result of having two GPUs identified as being on the same bus.   (See #1161).

Interesting, though: 
A local copy of FAHControl on that remote machine can successfully display the information for all of the slots on that FAHClient via 127.0.0.1, so FAHClient itself is healthy ... just the telnet processing is messed up..

**Comment by bb30994** [comment]
Here is a sample log.txt that FAHClient is attempting to parse.  I don't know to open FAHClient to append to an existing file so I can't reproduce it from this file without processing the same project(s).

FAHClient is running on Linux and FAHControl is running on Windows.
[log.txt](https://github.com/FoldingAtHome/fah-client-pub/files/278057/log.txt)

I suspect this will be closed as a duplicate when @1131 is resolved.

**Comment by jcoffland** [comment]
Should be fixed in v7.4.15.
