### ISSUE TITLE
FAHClient hangs

### ISSUE THREAD

**Issue by bb30994** [FoldingAtHome/fah-client-pub#1165]
Something strange is going on, and FAHClient enters a loop, consuming one CPU and preventing FAHControl from seeing updates to the log,

There is a high  probability that Project 116xx is putting something in the FAHCore's log that FAHClient cannot handle.  It's unclear whether this could/should be fixed in  either the Core or the Client.

The following characteristics are commonly observed::

    FAH has just completed a 116xx WU.
    Client processes the WU completion but then hangs
    Fahcontrol locally or remotely cannot connect
    No further messages are logged. The other FAH work units continue to be processed but even if they complete they are not uploaded.
    If the client restarts they do not upload (in my experience), and simply start over folding from 0%.

Note: Point 5 is most likely the known problem [#1166] where if a WU is interrupted after reaching 100% but before completing the tar/zip of the files, it cannot be resumed. There's no checkpoint-like recovery of a WU that will restart the tar/zip processing.

**Comment by bb30994** [comment]
Based on one report: 
> The thread in fahclient that is stuck is running near some code that prints messages like "Size of positions " ... " does not match topology " - which leads me to think there's a bug in fahclient result verification code that may lead to an infinite loop or something like that, with some very specific edge cases in the work output.

**Comment by jcoffland** [comment]
Actually this sounds like the Gromacs code which we use to read in Gromacs core trajectories.  This has always been a problem area.  The Gromacs code can crash if it does not like the files it's reading.  This messes up the whole client.

**Comment by bb30994** [comment]
OK, but somehow FAHClient should be able to insolate itself from whatever the FAHCore can  do before exiting.  How would a FILE_IO_ERROR during the core shutdown produce a loop in FAHClient without it being able to force the problematic code to abort so FAHClient, itself, can continue?.


I see one case where the end of the cores logfile_01.txt looks like this:

Leaving Run
- Writing 16337025 bytes of core data to disk...
Done: 16336513 -> 15971116 (compressed to 97.7 percent)
  ... Done.
Error deleting frame files
- Shutting down core

Folding@home Core Shutdown: FILE_IO_ERROR

**Comment by sgstair** [comment]
In case you're interested I have a few memory dump files taken from fahclient that's stuck in this state, please feel free to contact me to get access if you'd like to look.

**Comment by jcoffland** [comment]
I believe this was fixed by v7.4.10.  Reopen if not.
