### ISSUE TITLE
Wish fah-control tray icon context menu had option to pause or resume first gpu when multiple gpus are folding and according icon

### ISSUE THREAD

**Issue by informatorius** [FoldingAtHome/fah-client-pub#1171]
My system has multiple GPUs folding and sometimes I need to pause first GPU to use it for other purposes. I wish the fah-control tray icon contect menu had an option to pause or resume first gpu only. This would be much quicker than open the full fah-control UI and pause the slot there. Also the tray icon should then change to another symbol to signal first gpu it paused.

**Comment by jcoffland** [comment]
This issue should have been filed against [FAHControl](https://github.com/FoldingAtHome/fah-control).  However, I believe what you ask is already possible.  Right click on the slot in the slot list and you should get a menu which allows you to pause the specific slot.

**Comment by informatorius** [comment]
I wish this would be available in FahClient tray icon context menu.
